### ISSUE TITLE
Cannot add several items to order

### ISSUE THREAD

**Issue by lebe1** [augustin-wien/augustin-backend#53]
Cannot add several items to order leading to error "  "error": {
    "message": "commit unexpectedly resulted in rollback"
  }"
![Screenshot from 2023-09-22 11-44-27](https://github.com/augustin-wien/augustin-backend/assets/38591956/ff38e894-c146-4238-ada8-969f59acb76f)
![Screenshot from 2023-09-22 11-44-33](https://github.com/augustin-wien/augustin-backend/assets/38591956/3c64ad1f-87b9-457e-877d-1d9cd85a0141)

**Comment by jofmi** [comment]
Cannot reproduce. Can you share the log entries from go?
