### ISSUE TITLE
Balances did not change after payment

### ISSUE THREAD

**Issue by lebe1** [augustin-wien/augustin-backend#54]
Note: I did refresh my db-eaver and noticed this error since I received an error in [/payments/payout/](http://localhost:3000/swagger/index.html#/Payments/post_payments_payout_) saying "payout amount bigger than vendor account balance"
![image](https://github.com/augustin-wien/augustin-backend/assets/38591956/bb30f1ae-f809-4153-baf8-8841cb15a9f0)
![Screenshot from 2023-09-22 11-50-51](https://github.com/augustin-wien/augustin-backend/assets/38591956/0077c19d-48c0-41f5-b501-3c1ec9d4c963)

**Comment by jofmi** [comment]
Cannot reproduce

**Comment by jofmi** [comment]
Cannot reproduce with the following test: https://github.com/augustin-wien/augustin-backend/pull/66

Can you check if this error persists after the most recent changes are merged?
