### ISSUE TITLE
Log info in test 'No authorization header'

### ISSUE THREAD

**Issue by lebe1** [augustin-wien/augustin-backend#88]
Locally I receive a log message about an authorization header not being setup.

![Screenshot from 2023-10-01 16-48-52](https://github.com/augustin-wien/augustin-backend/assets/38591956/49e4a395-2e35-4b90-8d47-e71eb0ab14fa)

**Comment by nanu-c** [comment]
I have improved the failure message, this can be closed and a new issue can be opened if something similar comes up in the future.
