### ISSUE TITLE
Improve REST logs

### ISSUE THREAD

**Issue by nanu-c** [augustin-wien/augustin-backend#89]
Currently the logs look like 
![image](https://github.com/augustin-wien/augustin-backend/assets/404058/bf0aeb58-73e7-4058-aa30-376237b8e095)
that isn't really useful. We should add at least the full url.

**Comment by lebe1** [comment]
![image](https://github.com/augustin-wien/augustin-backend/assets/38591956/935dfa21-b424-4e0e-b397-580fa7561488)
This issues seems to be resolved, doesnt it @nanu-c ?

**Comment by nanu-c** [comment]
That's true, they look now differently
